// This file is auto-generated by scripts/generate-compiled-assets.ts
// DO NOT EDIT MANUALLY
// Target: bun-darwin-arm64

import difftasticArchiveLicense from '../../tools/archives/difftastic-LICENSE' assert { type: 'file' };
import ripgrepArchiveLicense from '../../tools/archives/ripgrep-LICENSE' assert { type: 'file' };
import difftasticLicense from '../../tools/licenses/difftastic-LICENSE' assert { type: 'file' };
import ripgrepLicense from '../../tools/licenses/ripgrep-LICENSE' assert { type: 'file' };

import difftasticArm64Darwin from '../../tools/archives/difftastic-arm64-darwin.tar.gz' assert { type: 'file' };
import ripgrepArm64Darwin from '../../tools/archives/ripgrep-arm64-darwin.tar.gz' assert { type: 'file' };

const PLATFORM_ASSETS: EmbeddedAsset[] = [
    asset('tools/archives/difftastic-arm64-darwin.tar.gz', difftasticArm64Darwin),
    asset('tools/archives/ripgrep-arm64-darwin.tar.gz', ripgrepArm64Darwin)
];

export interface EmbeddedAsset {
    relativePath: string;
    sourcePath: string;
}

function asset(relativePath: string, sourcePath: string): EmbeddedAsset {
    return {
        relativePath,
        sourcePath
    };
}

const COMMON_ASSETS: EmbeddedAsset[] = [
    asset('tools/archives/difftastic-LICENSE', difftasticArchiveLicense),
    asset('tools/archives/ripgrep-LICENSE', ripgrepArchiveLicense),
    asset('tools/licenses/difftastic-LICENSE', difftasticLicense),
    asset('tools/licenses/ripgrep-LICENSE', ripgrepLicense)
];

export async function loadEmbeddedAssets(): Promise<EmbeddedAsset[]> {
    return [
        ...COMMON_ASSETS,
        ...PLATFORM_ASSETS
    ];
}
