// This file is auto-generated by scripts/generate-compiled-assets.ts
// DO NOT EDIT MANUALLY
// Target: bun-windows-x64

import difftasticArchiveLicense from '../../tools/archives/difftastic-LICENSE' assert { type: 'file' };
import ripgrepArchiveLicense from '../../tools/archives/ripgrep-LICENSE' assert { type: 'file' };
import difftasticLicense from '../../tools/licenses/difftastic-LICENSE' assert { type: 'file' };
import ripgrepLicense from '../../tools/licenses/ripgrep-LICENSE' assert { type: 'file' };

import difftasticX64Win32 from '../../tools/archives/difftastic-x64-win32.tar.gz' assert { type: 'file' };
import ripgrepX64Win32 from '../../tools/archives/ripgrep-x64-win32.tar.gz' assert { type: 'file' };

const PLATFORM_ASSETS: EmbeddedAsset[] = [
    asset('tools/archives/difftastic-x64-win32.tar.gz', difftasticX64Win32),
    asset('tools/archives/ripgrep-x64-win32.tar.gz', ripgrepX64Win32)
];

export interface EmbeddedAsset {
    relativePath: string;
    sourcePath: string;
}

function asset(relativePath: string, sourcePath: string): EmbeddedAsset {
    return {
        relativePath,
        sourcePath
    };
}

const COMMON_ASSETS: EmbeddedAsset[] = [
    asset('tools/archives/difftastic-LICENSE', difftasticArchiveLicense),
    asset('tools/archives/ripgrep-LICENSE', ripgrepArchiveLicense),
    asset('tools/licenses/difftastic-LICENSE', difftasticLicense),
    asset('tools/licenses/ripgrep-LICENSE', ripgrepLicense)
];

export async function loadEmbeddedAssets(): Promise<EmbeddedAsset[]> {
    return [
        ...COMMON_ASSETS,
        ...PLATFORM_ASSETS
    ];
}
